version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-files/db
      dockerfile: Dockerfile
    image: dheenathayalanb/projectdb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql

  vproapp:
    build:
      context: ./Docker-files/app
      dockerfile: Dockerfile
    image: dheenathayalanb/projectapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps/

volumes:
  vproappdata: {}
  vprodbdata: {}